language: node_js
node_js:
  - "7"

before_install:
  # Repo for newer Node.js versions
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  directories:
  - $HOME/.yarn-cache

script:
  - npm run build

after_script:
  - cd ./docs
  - git add -A .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${gh_token}@${gh_ref}" master:${p_branch}

branches:
  only:
  - master

env:
  global:
    - gh_ref: github.com/cloud-templates/cloud-utils.git



